apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: travelplatform-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev

patches:
  # Override namespace in all resources
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: travelplatform-dev
    target:
      kind: ConfigMap
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: travelplatform-dev
    target:
      kind: Secret
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: travelplatform-dev
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: travelplatform-dev
    target:
      kind: Service
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: travelplatform-dev
    target:
      kind: Ingress

  # Minimal replicas for dev
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

  # Dev HPA
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
    target:
      kind: HorizontalPodAutoscaler

  # Dev ingress host
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-app.kadokadi.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev-app.kadokadi.com
    target:
      kind: Ingress

images:
  - name: ghcr.io/travelplatform/gateway
    newName: docker.io/travelplatform/gateway
    newTag: latest
  - name: ghcr.io/travelplatform/shuttle-service
    newName: docker.io/travelplatform/shuttle-service
    newTag: latest
  - name: ghcr.io/travelplatform/seat-service
    newName: docker.io/travelplatform/seat-service
    newTag: latest
  - name: ghcr.io/travelplatform/pricing-service
    newName: docker.io/travelplatform/pricing-service
    newTag: latest
  - name: ghcr.io/travelplatform/booking-service
    newName: docker.io/travelplatform/booking-service
    newTag: latest
  - name: ghcr.io/travelplatform/payment-service
    newName: docker.io/travelplatform/payment-service
    newTag: latest
  - name: ghcr.io/travelplatform/promo-service
    newName: docker.io/travelplatform/promo-service
    newTag: latest
  - name: ghcr.io/travelplatform/notification-service
    newName: docker.io/travelplatform/notification-service
    newTag: latest
